export const CURL = "http://localhost:3000/"

export const BASE_URL ="http://localhost:7001/"
export const PRODUCT_LIST = BASE_URL+"productlist"
export const SINGLE_PRODUCT = BASE_URL+"singleproduct?_id="
export const INCRE_QTY =BASE_URL+"customer/incrQuantity?product_id="
export const DECRE_QTY =BASE_URL+"customer/dcrQuantity?product_id="
export const LOGIN = BASE_URL+"login"
export const REGISTER = BASE_URL+"register"
export const CUSTOMER = BASE_URL+ "customer/record?customer_id="
export const CUSTOMER_PIC = BASE_URL + "customer/profilepic?customer_id="
export const CHANGE_PASSWORD = BASE_URL + "customer/changepassword?id="
export const MANAGE_CUSTOMER = BASE_URL + "admin/managecustomer?id="
export const CUSTOMER_LIST = BASE_URL +"admin/admincustomer"
export const ADD_PRODUCT = BASE_URL + "admin/addproduct"
export const PRODUCT_FILTER = BASE_URL + "filter"
export const SEND_EMAIL = BASE_URL+ "senduserpasswordresetemail"
export const RESET_PASSWORD = BASE_URL+ "userpasswordreset?id="
export const CUSTOMER_EDIT_PROFILE= BASE_URL+"customer/editprofile?customer_id="
export const UPLOAD_DOC= BASE_URL+"customer/uploaddocument"
